### ISSUE TITLE
Use Airgram for Bot?

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#6]
Is it possible to use airgram for bot auth?
E.g. I want to use airgram for bot like so:
`const botApp = new Airgram({ token: ... });`
And for user like so:
`const userApp = new Airgram({ id: ..., hash: ... });`
In this case I can make advanced test cases, e.g. send message as user, receive message as bot. Because for now Telegram blocked usage of bot-to-bot messages: [Bots can not see messages from other bots](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots).

**Comment by esindger** [comment]
For bot authorization you should initialize airgram this way:
```const userApp = new Airgram({ id: ..., hash: ..., token: ... });```

**Comment by volodalexey** [comment]
But why do I need `id` and `hash` for bot? Take a look at two the most popular libraries:
[node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api#usage):
`const bot = new TelegramBot(token, {polling: true});`
[telegraf](https://github.com/telegraf/telegraf#examples):
`const bot = new Telegraf(process.env.BOT_TOKEN);`

**Comment by esindger** [comment]
Because Airgram and that libraries use different API. Telegraf (and other) makes requests by Bot API and [passes token as part of the URL](https://core.telegram.org/bots/api#making-requests). Airgram implements MTProto encryption protocol and login via method [`auth.importBotAuthorization`](https://github.com/airgram/airgram/blob/master/docs/telegram-methods.md#authimportbotauthorization), which has required parameters `api_id` and `api_hash`.
